# Generated by Django 2.2.3 on 2019-07-11 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatreferral',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 19, 34, 1, 969860, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatreferral',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('C', 'Confirm')], default='P', max_length=2),
        ),
    ]
